#!/usr/bin/env python3
"""Build F5 ICT exam_blueprint.json from MCQ / written slot plans."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from mcq_core_plan import MCQ_CORE_SEQUENCE, MCQ_SLOT_PLAN

_REPO = Path(__file__).resolve().parents[2]
_DEFAULT_CURRICULUM = _REPO / "Subjects/DSE-ICT/question-bank/curriculum_concepts.json"

_WRITTEN_IMPORT = __import__(
    "f5_ict_written_from_dse", fromlist=["WRITTEN_SLOT_PLAN"]
).WRITTEN_SLOT_PLAN

_FMT = Path(__file__).resolve().parents[1] / "paper-formatter"
if str(_FMT) not in __import__("sys").path:
    __import__("sys").path.insert(0, str(_FMT))
from written_slot_ranges import WRITTEN_SLOT_PARAGRAPHS  # noqa: E402


def _load_curriculum(path: Path) -> dict:
    return json.loads(path.expanduser().resolve().read_text(encoding="utf-8"))


def _mcq_topic(slot_index: int, curriculum: dict) -> str:
    order = curriculum.get("mcq_compulsory_slot_order") or []
    for row in order:
        if int(row.get("slot", 0)) == slot_index:
            return str(row.get("topic", ""))
    return ""


def build_f5_exam02_blueprint(
    *,
    academic_year: str = "2025-2026",
    title: str = "25-26 S5 ICT Exam02 Blueprint",
    curriculum_path: Path | None = None,
) -> dict[str, Any]:
    """Full 44-slot blueprint (30 MCQ + 6 乙 + 8 丙) for Term 2 Exam02."""
    curriculum_path = curriculum_path or _DEFAULT_CURRICULUM
    curriculum = _load_curriculum(curriculum_path)

    slots: list[dict[str, Any]] = []
    for i, (core, concepts) in enumerate(MCQ_SLOT_PLAN, start=1):
        slots.append(
            {
                "id": f"mcq-{i:02d}",
                "section": "mcq",
                "marks": 1,
                "core": core,
                "topic": _mcq_topic(i, curriculum),
                "concepts": list(concepts),
                "question_type": "mcq",
                "dse_paper_types": ["Paper1_MultipleChoice", "Paper1A_MultipleChoice"],
                "layout": {"mcq_index": i},
            }
        )

    for slot_id, section, concepts, slugs, marks, title_slot in _WRITTEN_IMPORT:
        para = WRITTEN_SLOT_PARAGRAPHS.get(slot_id)
        layout: dict[str, Any] = {}
        if para:
            layout["paragraph_range"] = [para[0], para[1]]
        qtype = "sql" if "SQL" in concepts or slot_id.startswith("c-0") and slot_id != "c-01" else "structured"
        if slot_id == "c-01":
            qtype = "erd"
        if slot_id == "c-08":
            qtype = "algorithm"
        if "試算表" in concepts and slot_id == "b-01":
            qtype = "spreadsheet"
        slots.append(
            {
                "id": slot_id,
                "section": section,
                "marks": marks,
                "title": title_slot,
                "concepts": list(concepts),
                "question_type": qtype,
                "dse_paper_types": list(slugs),
                "layout": layout,
            }
        )

    return {
        "version": 1,
        "meta": {
            "title": title,
            "subject": "F5 ICT",
            "level": "S5",
            "academic_year": academic_year,
            "elective": "database",
            "total_marks": 100,
            "sections": {
                "mcq": {"marks": 30, "count": 30},
                "section_b": {"marks": 30, "count": 6},
                "section_c": {"marks": 40, "count": 7},
            },
            "mcq_core_sequence": list(MCQ_CORE_SEQUENCE),
            "concept_targets": {
                "數據庫": {"min": 3, "max": 12},
                "算法": {"min": 8, "max": 14},
                "試算表": {"min": 2, "max": 6},
                "數據控制": {"min": 1, "max": 6},
                "多媒體": {"min": 3, "max": 10},
            },
            "dse_year_pool": ["2021", "2022", "2023", "2024", "2025"],
            "concept_map": "Subjects/DSE-ICT/question-bank/concept_map.json",
            "style_patterns": "Subjects/DSE-ICT/question-bank/style_patterns.json",
            "notes": "Generated by f5_ict_exam_blueprint.py — edit slots before generate phase.",
        },
        "slots": slots,
    }


def load_blueprint(path: Path) -> dict[str, Any]:
    return json.loads(path.expanduser().resolve().read_text(encoding="utf-8"))


def save_blueprint(blueprint: dict[str, Any], path: Path) -> Path:
    path = path.expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(blueprint, ensure_ascii=False, indent=2), encoding="utf-8")
    return path
