"""Shared helpers for Python & AI (PAI) assignment testers.

Detects AI-generated code and caps marks for chapters where AI is prohibited.
"""

import re

AI_BAN_MARKS = 2
AI_BAN_THRESHOLD = 5

_STRONG_AI_PATTERNS = [
    (r"gemini", "Gemini"),
    (r"generativeai|GenerativeModel|google\.genai\b|genai\.", "Gemini API"),
    (r"chatgpt|openai\.|copilot|claude|deepseek", "其他 AI 工具"),
    (r"AI生成|使用\s*Gemini|Generated by|Google AI Studio", "AI 署名"),
]

_WEAK_AI_PATTERNS = [
    (r'if\s+__name__\s*==\s*["\']__main__["\']', "main guard", 2),
    (r"import\s+traceback", "traceback", 2),
    (r"import\s+zhconv", "zhconv", 2),
    (r"from\s+googletrans\s+import|import\s+googletrans", "googletrans", 2),
    (r"class\s+\w+[^:]*:", "class 定義", 2),
    (r'def\s+\w+\([^)]*\):\s*\n\s+"""', "函數 docstring", 1),
    (r'"""[\s\S]{100,}"""', "長 docstring", 2),
    (r"except\s+Exception\s+as\s+\w+:", "broad except", 1),
    (r"logging\.|import\s+logging", "logging", 3),
    (r"from\s+typing\s+import|:\s*str\s*[,)]|:\s*int\s*[,)]", "type hints", 2),
]


def read_student_code(filepath):
    """Read a Python file, normalising smart quotes."""
    try:
        with open(filepath, encoding="utf-8") as f:
            code = f.read()
    except Exception:
        with open(filepath, encoding="latin-1") as f:
            code = f.read()
    for old, new in (("“", '"'), ("”", '"'), ("‘", "'"), ("’", "'")):
        code = code.replace(old, new)
    return code


def detect_ai_usage(code, chapter=None):
    """Return (is_banned, score, reasons). Chapters 1–4 prohibit AI assistance."""
    score = 0
    reasons = []

    for pattern, label in _STRONG_AI_PATTERNS:
        if re.search(pattern, code, re.I):
            score += 10
            reasons.append(label)

    for pattern, label, points in _WEAK_AI_PATTERNS:
        if re.search(pattern, code, re.I | re.M):
            score += points
            reasons.append(label)

    lines = len(code.splitlines())
    if chapter is not None and chapter <= 2:
        if lines > 60:
            score += 2
            reasons.append(f"程式過長 ({lines} 行)")
        if lines > 100:
            score += 3
            reasons.append(f"程式非常長 ({lines} 行)")

    func_count = len(re.findall(r"\bdef\s+\w+\s*\(", code))
    if chapter is not None and chapter <= 2 and func_count >= 4:
        score += 2
        reasons.append(f"函數過多 ({func_count} 個)")

    return score >= AI_BAN_THRESHOLD, score, reasons


def apply_ai_ban_if_needed(mark, comments, code, chapter):
    """Cap marks at AI_BAN_MARKS when AI usage detected (chapters 1–4 only)."""
    if chapter is None or chapter > 4:
        return mark, comments

    is_banned, score, reasons = detect_ai_usage(code, chapter)
    if not is_banned:
        return mark, comments

    reason_text = "、".join(list(dict.fromkeys(reasons))[:4])
    ban_note = (
        f"\n[X] 第{chapter}章禁止使用 Gemini/AI 協助完成課業"
        f"（偵測到：{reason_text}）\n"
        f"[-] 因使用 AI，分數設為 {AI_BAN_MARKS} 分（原分 {mark}）\n"
    )
    if not comments.startswith("[O]: Correct"):
        comments = "[O]: Correct\n[-]: Minor error\n[X]: Major error\n\n" + comments
    return AI_BAN_MARKS, comments + ban_note


def finalize_ch1_4_mark(mark, comments, filepath, chapter):
    code = read_student_code(filepath)
    return apply_ai_ban_if_needed(mark, comments, code, chapter)
